# ----------------------- server --------------------------------------

server.port=4448

# ------------------------ log ----------------------------------------

logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - [%-5level] - %-30.30logger{30} - %msg%n

# ------------------- node settings -----------------------------------

node.message.await_timeout=120
node.message.live_timeout=300

node.session.idle_timeout=180
node.session.await_timeout=120

# -------------------- ws protocol -----------------------------------

ws.message.size_limit=31457280
ws.message.send_time_limit=60000

# --------------------------------------------------------------------

proxyHub.version=1.4.1