# ----------------------- server --------------------------------------

server.port=4448

# ------------------------ log ----------------------------------------

logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - [%-5level] - %logger{36} - %msg%n

# ------------------- node settings -----------------------------------

node.message.await_timeout=120
node.message.live_timeout=300

node.session.idle_timeout=300

# -------------------- ws protocol -----------------------------------

ws.message.size_limit=5242880
ws.message.send_time_limit=60000